services:
   aml_admin_bundle.image_type_extension:
          class: Aml\Bundle\AdminBundle\Form\Extension\ImageTypeExtension
          tags:
              - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
