parameters:
#    aml_admin.example.class: Aml\Bundle\AdminBundle\Example

services:
#    aml_admin.example:
#        class: %aml_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
