parameters:
#    aml_admin.example.class: Aml\Bundle\AdminBundle\Example

services:
#    aml_admin.example:
#        class: %aml_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
   aml_admin_bundle.image_type_extension:
          class: Aml\Bundle\AdminBundle\Form\Extension\ImageTypeExtension
          tags:
              - { name: form.type_extension, alias: file }