<?php

namespace Aml\Bundle\BlogBundle\Repository;

use Aml\Bundle\BlogBundle\Entity\Article;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * Function to build request in order to filter blog articles
     *
     * @param $query
     * @param array $params
     * @param array $filters
     *
     * @return array
     */
    private function buildRequestByFilters($query, array $params = [], array $filters = []): array
    {
        if (isset($filters['category']) && !empty($filters['category'])) {
            $query
                ->innerJoin('a.category', 'c')
                ->andWhere("c.system_name LIKE :category");
            $params['category'] = $filters['category'];
        }

        if (isset($filters['tag']) && !empty($filters['tag'])) {
            $query
                ->innerJoin('a.tags', 't')
                ->andWhere("t.system_name LIKE :tag");
            $params['tag'] = '%' . $filters['tag'] . '%';
        }

        $query->setParameters($params);

        return $query;
    }

    /**
     * Retrieves public articles
     *
     * @param int $page
     * @param array $filters
     * @param int $limit
     *
     * @return Paginator
     */
    public function getPublicArticles(int $page = 1, array $filters = [], int $limit = 5): Paginator
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $firstResult = ($page - 1) * $limit;
        $qb
            ->select('a')
            ->from(Article::class, 'a')
            ->leftJoin('a.logo', 'm')
            ->where("a.public = 1")
            ->orderBy('a.created', 'DESC');

        if (!empty($filters)) {
            $qb = $this->buildRequestByFilters($qb, [], $filters);
        }

        $qb
            ->setFirstResult($firstResult)
            ->setMaxResults($limit);

        return new Paginator($qb->getQuery());
    }

    /**
     * Fonction qui permet de supprimer les mots clés libres d'une discussion pour les rajouter proprement
     *
     * @param unknown_type $blog
     */
    public function cleanTags($blog)
    {
        $em = $this->getEntityManager();
        foreach ($blog->getTags() as $tag) {
            $blog->removeTag($tag);
        }
        $em->flush();
    }

    /**
     * Find article by url key
     *
     * @param $urlKey
     * @return mixed|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getArticleByUrlKey($urlKey)
    {
        $q = $this->getEntityManager()->createQueryBuilder();
        $q
            ->select('e')
            ->from(Article::class, 'e')
            ->join('e.url', 'u')
            ->where('u.urlKey = :url_key')
            ->setMaxResults(1);

        $params = [
            'url_key' => $urlKey,
        ];

        $q->setParameters($params);

        $query = $q->getQuery();

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
