<?php

namespace Aml\Bundle\BlogBundle\Repository;

use Aml\Bundle\BlogBundle\Entity\Article;
use Aml\Bundle\BlogBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    /**
     * Function pour récupérer les mots clés pour l'autocomplétion
     * @param string $value
     * @return array
     */
    public function getCategoriesWithNbArticles()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb
            ->select('c.systemName','c.name','count(a.id) as nbArticles','c.description')
            ->from(Article::class, 'a')
            ->innerJoin(Category::class, 'c','WITH', 'c.id=a.category')
            ->where('a.public = 1')
            ->groupBy('c.id')
            ->orderBy('c.name', 'ASC')
        ;

        $query = $qb->getQuery();
        return $query->getResult();
    }
}
