<?php

namespace Aml\Bundle\BlogBundle\Repository;

use Aml\Bundle\BlogBundle\Entity\Tags;
use Doctrine\ORM\EntityRepository;

/**
 * TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsRepository extends EntityRepository
{
    /**
     * Function pour récupérer les mots clés pour l'autocomplétion
     * @param string $value
     * @return array
     */
    public function getTags($value)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('t')
            ->from(Tags::class, 't')
            ->where("t.name LIKE :tag")
            ->orderBy('t.name', 'ASC')
            ->setParameter('tag', $value . '%');

        $query = $qb->getQuery();
        $tags = $query->getResult();

        $json = [];
        foreach ($tags as $mot) {
            $json[] = [
                'label' => $mot->getName(),
                'value' => $mot->getId(),
            ];
        }

        return $json;
    }

    /**
     * Funtion to load TumblrTab by name
     *
     * @param string $tag
     * @return boolean
     */
    public function loadOneTagByName($tag)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT bt.id,bt.name FROM AmlBlogBundle:Tags bt WHERE bt.name LIKE :tag')
            ->setParameter('tag', $tag);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return false;
        }

    }
}
