parameters:
#    aml_discography.example.class: Aml\Bundle\DiscographyBundle\Example

services:
    aml_discography.sitemap.generate:
        class: Aml\Bundle\DiscographyBundle\EventListener\SitemapListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
        tags:
            - { name: kernel.event_listener, event: aml_web.sitemap.generate_start, method: onGenerateSitemapEvent }

