parameters:
#    aml_discography.example.class: Aml\Bundle\DiscographyBundle\Example

services:
#    aml_discography.example:
#        class: %aml_discography.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
