parameters:
    aml_contact_us.subribers: "%admin_email%"

services:
    sonata.block.service.contact_us_messages:
          class: App\Block\Service\AdminMessagesBlockService
          arguments:
              - 'sonata.block.service.contact_us_messages'
              - '@templating'
              - '@doctrine.orm.entity_manager'
          tags:
              - { name: sonata.block }

    aml_contactus.message.post:
        class: App\EventListener\PostListener
        tags:
            - { name: kernel.event_listener, event: aml_contactus.message.post_sent, method: onPostEvent }
        arguments:
            - '@mailer'
            - '@doctrine.orm.entity_manager'
            - '%aml_contact_us.subribers%'

    App\Contact\ContactMessage:
        public: true
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@mailer'
          - '@event_dispatcher'
