parameters:
#    aml_medias.example.class: App\Example

services:
    aml_medias.google.client:
        class: App\Google\Client
        arguments:
          - '@logger'
          - '%google_app_name%'
          - '%google_developer_key%'

    aml_medias.google.youtube_provider:
        class: App\Google\YoutubeProvider
        arguments:
          - '@aml_medias.google.client'
          - '%youtube_username%'

    aml_medias.video.video_manager:
        class: App\Video\VideoManager
        arguments:
          - '@doctrine.orm.entity_manager'

    aml_medias.video.video_factory:
        class: App\Video\VideoFactory
