parameters:
#    aml_medias.example.class: App\Example

services:
    aml_medias.google.client:
        class: App\Google\Client
        arguments:
          - '@logger'
          - '%env(GOOGLE_APP_NAME)%'
          - '%env(GOOGLE_DEVELOPER_KEY)%'

    aml_medias.google.youtube_provider:
        class: App\Google\YoutubeProvider
        arguments:
          - '@aml_medias.google.client'
          - '%env(YOUTUBE_USERNAME)%'

    aml_medias.video.video_manager:
        class: App\Video\VideoManager
        arguments:
          - '@doctrine.orm.entity_manager'

    aml_medias.video.video_factory:
        class: App\Video\VideoFactory
