parameters:
#    aml_url_rewrite.example.class: Aml\Bundle\UrlRewriteBundle\Example

services:
#    aml_url_rewrite.example:
#        class: %aml_url_rewrite.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
