twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'form/material_design_layout.html.twig'
        - 'bootstrap_4_layout.html.twig'
    globals:
        project_name: '%env(APP_PROJECT_NAME)%'
        site_name: '%env(APP_SITE_NAME)%'
