php_version: 7

global_exclude_dirs:
  - vendor
  - vendors
  - test
  - tests
  - Tests
  - spec
  - features
  - Fixtures
  - DataFixtures
  - var
  - docker


ignore_branches:
  - gh-pages

commit_failure_conditions:
  - "pr.severity.critical > 0"
  - "pr.severity.major > 3"
