language: php
sudo: false

php:
  - '7.1'

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update

install:
  - composer install -o -n
  - php bin/console doctrine:schema:drop --force --env=test
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load --env=test -n

script:
  - vendor/bin/phpunit

notifications:
  email:
    -  aurelien.giry@gmail.com
