language: php
sudo: false

php:
  - '7.1'

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update

install:
  - composer install -o -n
  - bin/console doctrine:schema:drop --force --env=test
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:update --force --env=test
  - bin/console doctrine:fixtures:load --env=test -n

script:
  - bin/console lint:twig templates
  - bin/console lint:yaml config
  - vendor/bin/phpunit
  - vendor/bin/phpunit --coverage-clover build/coverage/xml
  - bin/console security:check

after_script:
  - vendor/bin/codacycoverage clover build/coverage/xml

notifications:
  email:
    -  aurelien.giry@gmail.com
