language: php
sudo: false

php:
  - '7.0'
  - '7.1'

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer require --dev --no-update phpunit/phpunit 6.1.2
  - composer self-update

install:
  - composer install -o --no-scripts
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:schema:update --force --env=test

script:
  - vendor/bin/simple-phpunit

notifications:
  email:
    -  aurelien.giry@gmail.com