language: php, node_js
sudo: false

php:
  - '7.1'
node_js:
  - 12

cache: yarn

before_install:
  - cat /etc/*-release
  - sudo apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
  - sudo apt-get install -y nodejs
  - nodejs --version
  - nvm use system
  - sudo npm install -g yarn
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update

install:
  - composer install -o -n
  - bin/console doctrine:schema:drop --force --env=test
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:update --force --env=test
  - bin/console doctrine:fixtures:load --env=test -n

script:
  - bin/console lint:twig templates
  - bin/console lint:yaml config
  - yarn install
  - yarn encore dev
  - bin/phpunit

notifications:
  email:
    -  aurelien.giry@gmail.com
