<?php

namespace Aml\Bundle\MediasBundle\Entity\Repository\Video;

use Aml\Bundle\MediasBundle\Entity\Repository\VideoRepository;

/**
 * DailymotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailymotionRepository extends VideoRepository
{
}
