<?php

namespace Aml\Bundle\MediasBundle\Entity\Repository\Video;

use Doctrine\ORM\EntityRepository;

use Aml\Bundle\MediasBundle\Entity\Repository\VideoRepository;

/**
 * YoutubeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YoutubeRepository extends VideoRepository
{
}