<?php

namespace Aml\Bundle\WebBundle\Repository\Video;

use Aml\Bundle\WebBundle\Repository\VideoRepository;

/**
 * YoutubeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YoutubeRepository extends VideoRepository
{
}
