services:
    aml_blog.sitemap.generate:
        class: Aml\Bundle\BlogBundle\EventListener\SitemapListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
        tags:
            - { name: kernel.event_listener, event: aml_web.sitemap.generate_start, method: onGenerateSitemapEvent }

    Aml\Bundle\BlogBundle\Article\ArticleManager:
        arguments:
            - '@doctrine.orm.default_entity_manager'