services:
    Aml\Bundle\BlogBundle\EventListener\SitemapListener:
        autowire: true
        tags:
            - name: kernel.event_subscriber

    Aml\Bundle\BlogBundle\Article\ArticleManager:
        autowire: true
