aml_medias:
    resource: "@AmlMediasBundle/Resources/config/routing.yml"
    prefix:   /

aml_evenements:
    resource: "@AmlEvenementsBundle/Controller/"
    type:     annotation
    prefix:   /

aml_users:
    resource: "@AmlUsersBundle/Controller/"
    type:     annotation
    prefix:   /

aml_blog:
    resource: "@AmlBlogBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

AmlWebBundle:
    resource: "@AmlWebBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    pattern:   /connexion
    defaults:  { _controller: AmlUsersBundle:Secure:login }
    
login_check:
    pattern:   /login_check
    
_imagine:
    resource: .
    type:     imagine