jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
       # Symfony\Component\Security\Core\User\User: plaintext
       Aml\Bundle\UsersBundle\Entity\User:
             algorithm: sha512
             iterations: 2000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        users:
            entity: { class: AmlUsersBundle:User, property: login }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/*
            provider: users            
            form_login:
                check_path: /login_check
                login_path: /connexion
                                
            remember_me:
                key:      "%secret%"
                lifetime: 2592000
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER  
                
            logout:
                path:   /deconnexion
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/admin, roles: [ROLE_ADMIN,ROLE_SUPER_ADMIN,IS_AUTHENTICATED_REMEMBERED] }
        #- { path: ^/zend, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY } 