# Aml\Bundle\ContactUsBundle/Resources/config/admin.yml
services:
    sonata.admin.contactus:
        class: Aml\Bundle\ContactUsBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administration, label: "Formulaire de contact" }
        arguments:
            - ~
            - Aml\Bundle\ContactUsBundle\Entity\Message
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlContactUsBundle]]
