aml_contact_us_index:
    pattern:  /contact-us
    defaults: { _controller: AmlContactUsBundle:Default:index }
aml_contact_us_post:
    pattern:  /contact-us/post
    defaults: { _controller: AmlContactUsBundle:Default:post }
