parameters:
    aml_contact_us.subriber: "%admin_email%"

services:
    aml_contactus.message.post:
            class: Aml\Bundle\ContactUsBundle\EventListener\PostListener
            arguments:
                mailer: "@mailer"
                container: "@service_container"
            tags:
                - { name: kernel.event_listener, event: aml_contactus.message.post_sent, method: onPostEvent }
