<?php

declare(strict_types=1);

/*
 * This file is part of the AML87 application.
 * (c) Aurélien GIRY <aurelien.giry@gmail.com>
 */

namespace App\Repository;

use App\Entity\Link;
use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{
    /**
     * Function to load public links.
     *
     * @return array
     */
    public function getPublicLinks()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb
            ->select('l')
            ->from(Link::class, 'l')
            ->where('l.public = 1')
            ->orderBy('l.weight', 'ASC');

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
