# Aml\Bundle\EvenementsBundle/Resources/config/admin.yml
services:
    sonata.admin.evenement:
        class: Aml\Bundle\EvenementsBundle\Admin\EvenementAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Agenda, label: "Evenements" }
        arguments:
            - ~
            - Aml\Bundle\EvenementsBundle\Entity\Evenement
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlEvenementsBundle]]


