services:
    aml_evenements.sitemap.generate:
        class: Aml\Bundle\EvenementsBundle\EventListener\SitemapListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
        tags:
            - { name: kernel.event_listener, event: aml_web.sitemap.generate_start, method: onGenerateSitemapEvent }

    Aml\Bundle\EvenementsBundle\Evenement\EvenementManager:
        class: Aml\Bundle\EvenementsBundle\Evenement\EvenementManager
        arguments: ['@doctrine.orm.entity_manager']
