<?php

/*
 * This file is part of the AML87 application.
 * (c) Aurélien GIRY <aurelien.giry@gmail.com>
 */

namespace App\Media\Infrastructure\Doctrine;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageDoctrineRepository extends EntityRepository
{
}
