<?php

namespace Aml\Bundle\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
	
	public function countPublicArticles(){
		$em = $this->getEntityManager();		
			$qb = $em->createQueryBuilder();
			
			$qb
				->select('COUNT(a.id)')
				->from('AmlBlogBundle:Blog', 'a')
				->where("a.public = 1")	
			;
	
			$query = $qb->getQuery();
			
			//echo $query->getSql(); var_dump($query->getParameters());exit;
			
			
			
			return $query->getSingleScalarResult();
	}
}