<?php

namespace Aml\Bundle\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogTagsRepository extends EntityRepository
{
    /**
     * Funtion to load TumblrTab by name
     *
     * @param string $tag
     * @return boolean
     */
    public function loadOneTagByName($tag)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT bt.id,bt.name FROM AmlBlogBundle:BlogTags bt WHERE bt.name LIKE :tag')
            ->setParameter('tag', $tag);

        try
        {
            $result = $query->getSingleResult();
            return $result;

        } catch (\Doctrine\ORM\NoResultException $e)
        {
            return false;
        }

    }
}