<?php

/*
 * This file is part of the AML87 application.
 * (c) Aurélien GIRY <aurelien.giry@gmail.com>
 */

namespace App\Discography\Infrastructure\Doctrine;

use App\Discography\Domain\Model\Album;
use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumDoctrineRepository extends EntityRepository
{
    public function getAlbumByUrlKey($urlKey)
    {
        $q = $this->getEntityManager()->createQueryBuilder();
        $q
            ->select('e')
            ->from(Album::class, 'e')
            ->join('e.url', 'u')
            ->where('u.urlKey = :url_key')
            ->setMaxResults(1);

        $params = ['url_key' => $urlKey];

        $q->setParameters($params);

        return $q->getQuery()->getOneOrNullResult();
    }
}
