<?php

/*
 * This file is part of the AML87 application.
 * (c) Aurélien GIRY <aurelien.giry@gmail.com>
 */

namespace App\Discography\Infrastructure\Doctrine;

use Doctrine\ORM\EntityRepository;

/**
 * TrackRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackDoctrineRepository extends EntityRepository
{
}
