security:
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /.*
            http_basic:
                realm: "Secured Area"
            logout: true
            security: true
            anonymous: true
