imports:
    - { resource: parameters.yaml }
    - { resource: security.yaml }
    - { resource: services.yaml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
          project_name: "%project_name%"
          site_name: "%site_name%"
#    form:
#          resources:
#              - 'SonataCoreBundle:Form:datepicker.html.twig'
              #- 'bootstrap_3_layout.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 5.6
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Sonata Admin
sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text: ~
        sonata.block.service.rss: ~
        sonata.admin.block.search_result: ~
        sonata.block.service.contact_us_messages: ~

sonata_admin:
    title:      AML87
    title_logo: /bundles/amlweb/images/logo_aml87_black.png
    templates:
        # default global templates
        layout:  AmlAdminBundle::standard_layout.html.twig
        #layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        #list:    AmlAdminBundle:CRUD:list.html.twig
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

        # Block
        #list_block: AmlAdminBundle:Block:block_admin_list.html.twig
        list_block: SonataAdminBundle:Block:block_admin_list.html.twig

       # dashboard:  AmlAdminBundle:Core:dashboard.html.twig
        dashboard:  SonataAdminBundle:Core:dashboard.html.twig

    dashboard:
        blocks:
            - { position: right, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata.block.service.text, settings: { content: '<div class="box"><div class="box-header with-border"><h2>Bienvenue !</h2></div><div class="box-body">Bienvenue dans la partie administrable du site.</div></div>'} }
            - { position: left, type: sonata.block.service.contact_us_messages }
            #- { position: center, type: sonata.timeline.block.timeline, settings: { context: SONATA_ADMIN, max_per_page: 25 }}
            #- { position: right, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 7, mode: admin }}
            #- { position: right, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 7, mode: admin }}
            #- { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}



# Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    write_to:       "%kernel.root_dir%/../web"
#    use_controller: false
#    bundles:        [AmlWebBundle, TwigBundle]
#    filters:
#        cssrewrite: ~

sonata_intl:
    timezone:
        # default timezone used as fallback
        default: Europe/Paris

        # locale specific overrides
        locales:
            fr: Europe/Paris
            en_UK: Europe/London

# FOS User Bundle
#fos_user:
#    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
#    firewall_name: main
#    user_class: App\Entity\User
#    from_email:
#      address:        noreply@aml87.fr
#      sender_name:    "%site_name%"
    #profile:
     #   form:
      #      type: aml_user_profile



# KNP Menu
knp_menu:
    providers:
        builder_alias: false    # disable the builder-based provider
        container_aware: true   # keep this one enabled. Can be omitted as it is the default


## Sentry
sentry:
    dsn: "%sentry_dsn%"
    app_path: "%kernel.root_dir%/.."
    client: Sentry\SentryBundle\SentrySymfonyClient
    options:
        environment: "%kernel.environment%"
        error_types: E_ALL & ~E_DEPRECATED & ~E_NOTICE
        prefixes:
            - "%kernel.root_dir%/.."
        excluded_app_paths:
            - "%kernel.root_dir%/../vendor"
            - "%kernel.root_dir%/../var/cache"
    exception_listener: Sentry\SentryBundle\EventListener\ExceptionListener
    skip_capture:
        - "Symfony\\Component\\HttpKernel\\Exception\\HttpExceptionInterface"




