parameters:
    app_google_analytics.account_id: '%env(GOOGLE_ANALYTICS_ACCOUNT_ID)%'
    locale: 'fr'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # Service Configuration
#    twig.extension.text:
#        class: Twig_Extensions_Extension_Text
#        tags:
#           - { name: twig.extension }
#
#    twig.extension.intl:
#        class: Twig_Extensions_Extension_Intl
#        tags:
#           - { name: twig.extension }

#    aml.twig.word_warp_extension:
#        class: App\Twig\WordWarpExtension
#        tags:
#          - { name: twig.extension }

#    aml.twig.nice_date_extension:
#        class: App\Twig\PublicStatusExtension
#        tags:
#            - { name: twig.extension }
#
#    aml.twig.substring_extension:
#        class: App\Twig\SubstringExtension
#        tags:
#          - { name: twig.extension }


    ## KNP
    app.menu_builder:
        class: App\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    Knp\Menu\MenuItem: # the service definition requires setting the class
        factory: ["@app.menu_builder", createMainMenu]
        arguments:
            - "@request_stack"
        tags:
            - { name: knp_menu.menu, alias: app_main_menu } # The alias is what is used to retrieve the menu

    app.breadcrumb_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", createBreadcrumbMenu]
        arguments:
            - "@request_stack"
        tags:
            - { name: knp_menu.menu, alias: app_breadcrumb } # The alias is used in the template

    ## Data Fixtures
    App\DataFixtures\PageFixtures:
        tags: ['doctrine.fixture.orm']

    App\DataFixtures\BlogFixtures:
        tags: ['doctrine.fixture.orm']

    App\DataFixtures\DiscographyFixtures:
        tags: ['doctrine.fixture.orm']

    App\DataFixtures\EvenementFixtures:
        tags: ['doctrine.fixture.orm']

    ## Article
    App\Article\ArticleManager:
        public: true

    ## Discography
    App\Discography\DiscographyManager:
        public: true

    ## Google
    App\Google\Client:
        arguments:
          - '@logger'
          - '%env(GOOGLE_APP_NAME)%'
          - '%env(GOOGLE_DEVELOPER_KEY)%'

    App\Google\YoutubeProvider:
        public: true
        arguments:
          - '@App\Google\Client'
          - '%env(YOUTUBE_USERNAME)%'

    ## Video
    App\Video\VideoManager:
        public: true

    App\Video\VideoFactory:
        public: true

    ## Contact
    App\EventListener\PostListener:
        arguments:
            $subscribers: '%env(APP_ADMIN_EMAIL)%'
        tags:
            name: kernel.event_subscriber

    App\Contact\ContactMessage:
        public: true
        autowire: true

    App\Form\Type\MessageType:
        arguments:
            $reCAPTCHA_site_key: '%env(RECAPTCHA_SITE_KEY)%'
