<?php

namespace App\Repository\Video;

use App\Repository\VideoRepository;

/**
 * DailymotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailymotionRepository extends VideoRepository
{
}
