<?php

namespace Aml\Bundle\EvenementsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Season
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
    public function getSeasonByDateStart(\DateTime $eventDateStart)
    {
        $q = $this->getEntityManager()->createQueryBuilder();
        $q
            ->select('s')
            ->from('AmlEvenementsBundle:Season', 's')
            ->where('s.dateStart <= :eventDateStart')
            ->andWhere('s.dateEnd >= :eventDateStart')
            ->orderBy('s.dateStart', 'ASC')
            ->setMaxResults(1);

        $params = array(
            'eventDateStart' => $eventDateStart,
        );

        $q->setParameters($params);

        $query = $q->getQuery();

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}