<?php

namespace Aml\Bundle\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MusicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicRepository extends EntityRepository
{
}
