parameters:
#    tools_google_analytics.example.class: Tools\Bundle\GoogleAnalyticsBundle\Example
    tools_google_analytics.account_id: "%ga_account_id%"

services:
#    tools_google_analytics.example:
#        class: %tools_google_analytics.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
