parameters:
#    tools_youtube_api.example.class: Tools\Bundle\YoutubeApiBundle\Example

services:
    tools_youtube_api.init_client:
         class: Tools\Bundle\YoutubeApiBundle\Api\Youtube
         arguments:
            - "%google_app_name%"
            - "%google_developer_key%"

