# Aml\Bundle\UsersBundle/Resources/config/admin.yml
services:
    sonata.admin.link:
        class: Aml\Bundle\WebBundle\Admin\LinkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Autres contenus", label: "Liens" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Link
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    sonata.admin.page:
        class: Aml\Bundle\WebBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Autres contenus", label: "Page" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Page
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    sonata.admin.partner:
        class: Aml\Bundle\WebBundle\Admin\PartenaireAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Autres contenus", label: "Partenaires" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Partenaire
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]
    ## Blog
    sonata.admin.blog:
        class: Aml\Bundle\WebBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Blog, label: "Articles" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Article
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    sonata.admin.blog.tags:
        class: Aml\Bundle\WebBundle\Admin\TagsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Blog, label: "Tags" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Tags
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    sonata.admin.blog.categories:
        class: Aml\Bundle\WebBundle\Admin\CategoriesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Blog, label: "Categories" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Category
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]


    ## Contact
    sonata.admin.contactus:
        class: Aml\Bundle\WebBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administration, label: "Formulaire de contact" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Message
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    ## Discography
    sonata.admin.album:
        class: Aml\Bundle\WebBundle\Admin\AlbumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Discographie, label: "Albums" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Album
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    sonata.admin.album.tracks:
        class: Aml\Bundle\WebBundle\Admin\TrackAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Discographie, label: "Pistes" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Track
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    ## Evenements
    sonata.admin.evenement:
        class: Aml\Bundle\WebBundle\Admin\EvenementAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Agenda, label: "Evenements" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Evenement
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    sonata.admin.evenement.seasons:
        class: Aml\Bundle\WebBundle\Admin\SeasonAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Agenda, label: "Saisons" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Season
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    ## Medias
    sonata.admin.images:
          class: Aml\Bundle\WebBundle\Admin\ImageAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: Medias, label: "Images" }
          arguments:
              - ~
              - Aml\Bundle\WebBundle\Entity\Image
              - 'SonataAdminBundle:CRUD'
          calls:
              - [ setTranslationDomain, [AmlWebBundle]]
             # - [ setTemplate, [edit, AmlWebBundle:Admin:edit.html.twig]]

    sonata.admin.documents:
        class: Aml\Bundle\WebBundle\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Medias, label: "Documents" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\File
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    sonata.admin.videos:
        class: Aml\Bundle\WebBundle\Admin\VideoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Medias, label: "Videos" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Video\Youtube
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]






