# Aml\Bundle\UsersBundle/Resources/config/admin.yml
services:
    sonata.admin.link:
        class: Aml\Bundle\WebBundle\Admin\LinkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Autres contenus", label: "Liens" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Link
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    sonata.admin.page:
        class: Aml\Bundle\WebBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Autres contenus", label: "Page" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Page
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]

    sonata.admin.partner:
        class: Aml\Bundle\WebBundle\Admin\PartenaireAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Autres contenus", label: "Partenaires" }
        arguments:
            - ~
            - Aml\Bundle\WebBundle\Entity\Partenaire
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AmlWebBundle]]
