parameters:
#    aml_medias.example.class: Aml\Bundle\MediasBundle\Example

services:
    aml_medias.google.client:
        class: Aml\Bundle\MediasBundle\Google\Client
        arguments:
          - '@logger'
          - '%google_app_name%'
          - '%google_developer_key%'
