parameters:
#    aml_medias.example.class: Aml\Bundle\MediasBundle\Example

services:
    aml_medias.google.client:
        class: Aml\Bundle\MediasBundle\Google\Client
        arguments:
          - '@logger'
          - '%google_app_name%'
          - '%google_developer_key%'

    aml_medias.google.youtube_provider:
        class: Aml\Bundle\MediasBundle\Google\YoutubeProvider
        arguments:
          - '@aml_medias.google.client'
          - '%youtube_username%'

    aml_medias.google.google_calendar_provider:
        class: Aml\Bundle\MediasBundle\Google\GoogleCalendarProvider
        arguments:
          - '@aml_medias.google.client'
          - '%google_calendar_id%'

    aml_medias.video.video_manager:
        class: Aml\Bundle\MediasBundle\Video\VideoManager
        arguments:
          - '@doctrine.orm.entity_manager'

    aml_medias.video.video_factory:
        class: Aml\Bundle\MediasBundle\Video\VideoFactory
