<?php

namespace Aml\Bundle\WebBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogTagsRepository extends EntityRepository
{
}