<?php

namespace Aml\Bundle\WebBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{
    /**
     * Function to load public links
     * @return array
     */
    public function getPublicLinks(){
		$em = $this->getEntityManager();		
		$qb = $em->createQueryBuilder();
		
		$qb
			->select('l')
			->from('AmlWebBundle:Link', 'l')
			->where("l.public = 1")	
		;

		$query = $qb->getQuery();
		
		//echo $query->getSql(); var_dump($query->getParameters());exit;
		
		
		
		return $query->getResult();
	}
}